import Footer from "./common/footer";
import Header from "./common/header";
import Cursor from "./components/cursor/cursor";
import LenisScroll from "./components/scroll/lenisscroll";
import "./globals.scss";
import "./font.scss"
import "../styles/styles.scss";

export const metadata = {
  title: "Aristo Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="./favicon.png" rel="shortcut icon" type="image/x-icon" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Cursor />
        <LenisScroll />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
